In [28]:
#dot product

import numpy as np

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat1 = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat1.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat1[x][y], end=" ")  
    print()  


Rows= int(input("Give the number of rows:"))  
Columns= int(input("Give the number of columns:"))  
   
mat2 = []  
print("Please give the entries of matrix 2 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat2.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat2[x][y], end=" ")  
    print()  


res = np.dot(mat1,mat2)
 
print("dot product \n",res)


Give the number of rows: 2
Give the number of columns: 2


Please give the entries of matrix1 row-wise:


 1
 2
 3
 4


1 2 
3 4 


Give the number of rows: 2
Give the number of columns: 2


Please give the entries of matrix 2 row-wise:


 2
 3
 4
 5


2 3 
4 5 
dot product 
 [[10 13]
 [22 29]]


In [21]:
#transpose

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat[x][y], end
              =" ")  
    print()  

              
result = np.transpose(mat)
    
print("transpose \n",result)




Give the number of rows: 2
Give the number of columns: 2


Please give the entries of matrix1 row-wise:


 6
 9
 5
 8


6 9 
5 8 
transpose 
 [[6 5]
 [9 8]]


In [22]:
#trace

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat[x][y], end=" ")  
    print()  

              
result = np.trace(mat)
    
print("trace \n ",result)

Give the number of rows: 2
Give the number of columns: 2


Please give the entries of matrix1 row-wise:


 3
 6
 9
 8


3 6 
9 8 
trace 
  11


In [23]:
#rank

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat[x][y], end=" ")  
    print()  

              
result = np.linalg.matrix_rank(mat)
    
print("Rank of matrix \n" ,result)

Give the number of rows: 2
Give the number of columns: 2


Please give the entries of matrix1 row-wise:


 4
 6
 8
 9


4 6 
8 9 
Rank of matrix 
 2


In [33]:
#determinant

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat[x][y], end=" ")  
    print()  

              
result = np.linalg.det(mat)
    
print("Determinant of matrix \n" ,result)


Give the number of rows: 2
Give the number of columns: 2


Please give the entries of matrix1 row-wise:


 5
 6
 7
 8


5 6 
7 8 
Determinant of matrix 
 -1.999999999999999


In [26]:
#inverse

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat[x][y], end=" ")  
    print()  

              
result =np.linalg.inv(mat)
    
print("Inverse of matrix \n" ,result)

Give the number of rows: 2
Give the number of columns: 2


Please give the entries of matrix1 row-wise:


 4
 3
 6
 2


4 3 
6 2 
Inverse of matrix 
 [[-0.2  0.3]
 [ 0.6 -0.4]]


In [36]:
#eigen values

Rows = int(input("Give the number of rows:"))  
Columns = int(input("Give the number of columns:"))  
   
mat1 = []  
print("Please give the entries of matrix1 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat1.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat1[x][y], end=" ")  
    print()  


Rows= int(input("Give the number of rows:"))  
Columns= int(input("Give the number of columns:"))  
   
mat2 = []  
print("Please give the entries of matrix 2 row-wise:")  
  
# For user input  
for x in range(Rows):
    r = []  
    for y in range(Columns): 
        r.append(int(input()))  
    mat2.append(r)  


for x in range(Rows):  
    for y in range(Columns):  
        print(mat2[x][y], end=" ")  
    print()  


w, v = np.linalg.eig(mat1)

print("Printing the Eigen values of mat1\n", w)
print("Printing Right eigenvectors of mat1\n",v)

w, v = np.linalg.eig(mat2)


print("Printing the Eigen values of mat2\n", w)
print("Printing Right eigenvectors of mat2\n",v)



Give the number of rows: 2
Give the number of columns: 2


Please give the entries of matrix1 row-wise:


 2
 4
 6
 8


2 4 
6 8 


Give the number of rows: 2
Give the number of columns: 2


Please give the entries of matrix 2 row-wise:


 3
 6
 9
 5


3 6 
9 5 
Printing the Eigen values of mat1
 [-0.74456265 10.74456265]
Printing Right eigenvectors of mat1
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
Printing the Eigen values of mat2
 [-3.41619849 11.41619849]
Printing Right eigenvectors of mat2
 [[-0.68302051 -0.58049671]
 [ 0.73039919 -0.81426259]]
